/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package Analizador;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int PACK = 13;
  /** RegularExpression Id. */
  int LIBRARY = 14;
  /** RegularExpression Id. */
  int PUBLIC = 15;
  /** RegularExpression Id. */
  int PRIVATE = 16;
  /** RegularExpression Id. */
  int BREAK = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int FLOAT = 22;
  /** RegularExpression Id. */
  int BOOLEAN = 23;
  /** RegularExpression Id. */
  int TRY = 24;
  /** RegularExpression Id. */
  int CATCH = 25;
  /** RegularExpression Id. */
  int SUPER = 26;
  /** RegularExpression Id. */
  int THIS = 27;
  /** RegularExpression Id. */
  int DERIVATE = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int FINAL = 30;
  /** RegularExpression Id. */
  int VOID = 31;
  /** RegularExpression Id. */
  int NULL = 32;
  /** RegularExpression Id. */
  int IMPORT = 33;
  /** RegularExpression Id. */
  int TRUE = 34;
  /** RegularExpression Id. */
  int FALSE = 35;
  /** RegularExpression Id. */
  int FOR = 36;
  /** RegularExpression Id. */
  int SWITCH = 37;
  /** RegularExpression Id. */
  int CASE = 38;
  /** RegularExpression Id. */
  int ARRAY = 39;
  /** RegularExpression Id. */
  int PRINMAIN = 40;
  /** RegularExpression Id. */
  int DOUBLE = 41;
  /** RegularExpression Id. */
  int EXCEPT = 42;
  /** RegularExpression Id. */
  int DEF = 43;
  /** RegularExpression Id. */
  int LLAVA = 44;
  /** RegularExpression Id. */
  int LLAVC = 45;
  /** RegularExpression Id. */
  int CORA = 46;
  /** RegularExpression Id. */
  int CORC = 47;
  /** RegularExpression Id. */
  int PAREA = 48;
  /** RegularExpression Id. */
  int PAREC = 49;
  /** RegularExpression Id. */
  int PYC = 50;
  /** RegularExpression Id. */
  int COMSIM = 51;
  /** RegularExpression Id. */
  int COM = 52;
  /** RegularExpression Id. */
  int PUNT = 53;
  /** RegularExpression Id. */
  int GUIONB = 54;
  /** RegularExpression Id. */
  int DOSP = 55;
  /** RegularExpression Id. */
  int MAYORQ = 56;
  /** RegularExpression Id. */
  int MENORQ = 57;
  /** RegularExpression Id. */
  int MAYORI = 58;
  /** RegularExpression Id. */
  int MENORI = 59;
  /** RegularExpression Id. */
  int IGUALI = 60;
  /** RegularExpression Id. */
  int DIFER = 61;
  /** RegularExpression Id. */
  int AND = 62;
  /** RegularExpression Id. */
  int OR = 63;
  /** RegularExpression Id. */
  int NOT = 64;
  /** RegularExpression Id. */
  int INCRE = 65;
  /** RegularExpression Id. */
  int DECRE = 66;
  /** RegularExpression Id. */
  int ASIG = 67;
  /** RegularExpression Id. */
  int SUMASIG = 68;
  /** RegularExpression Id. */
  int RESASIG = 69;
  /** RegularExpression Id. */
  int MULASIG = 70;
  /** RegularExpression Id. */
  int DIVASIG = 71;
  /** RegularExpression Id. */
  int MODASIG = 72;
  /** RegularExpression Id. */
  int SUMA = 73;
  /** RegularExpression Id. */
  int RESTA = 74;
  /** RegularExpression Id. */
  int DIVIS = 75;
  /** RegularExpression Id. */
  int POTEN = 76;
  /** RegularExpression Id. */
  int MODUL = 77;
  /** RegularExpression Id. */
  int MULTI = 78;
  /** RegularExpression Id. */
  int letraMay = 79;
  /** RegularExpression Id. */
  int letraMin = 80;
  /** RegularExpression Id. */
  int c = 81;
  /** RegularExpression Id. */
  int digito = 82;
  /** RegularExpression Id. */
  int ENTERO = 83;
  /** RegularExpression Id. */
  int FLOTANTEDOUBLE = 84;
  /** RegularExpression Id. */
  int CLASES = 85;
  /** RegularExpression Id. */
  int CARACTER = 86;
  /** RegularExpression Id. */
  int CADENA = 87;
  /** RegularExpression Id. */
  int PAQUET = 88;
  /** RegularExpression Id. */
  int VAR = 89;
  /** RegularExpression Id. */
  int FUNC = 90;
  /** RegularExpression Id. */
  int LIBR = 91;
  /** RegularExpression Id. */
  int A = 92;
  /** RegularExpression Id. */
  int GRADOS = 93;
  /** RegularExpression Id. */
  int CPOR = 94;
  /** RegularExpression Id. */
  int PUNTOS = 95;
  /** RegularExpression Id. */
  int ACENTOI = 96;
  /** RegularExpression Id. */
  int ACENTO = 97;
  /** RegularExpression Id. */
  int BARRAI = 98;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\b\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"If\"",
    "\"Else\"",
    "\"While\"",
    "\"class\"",
    "\"Pack\"",
    "\"Library\"",
    "\"public\"",
    "\"private\"",
    "\"break\"",
    "\"do\"",
    "\"char\"",
    "\"string\"",
    "\"int\"",
    "\"float\"",
    "\"boolean\"",
    "\"Try\"",
    "\"Catch\"",
    "\"Super\"",
    "\"This\"",
    "\"Derivate\"",
    "\"return\"",
    "\"Final\"",
    "\"void\"",
    "\"null\"",
    "\"import\"",
    "\"true\"",
    "\"false\"",
    "\"For\"",
    "\"Switch\"",
    "\"Case\"",
    "\"Array\"",
    "\"principalMain\"",
    "\"double\"",
    "\"Except\"",
    "\"Default\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"\\\'\"",
    "\",\"",
    "\".\"",
    "\"_\"",
    "\":\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"<>\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"^\"",
    "\"%\"",
    "\"*\"",
    "<letraMay>",
    "<letraMin>",
    "<c>",
    "<digito>",
    "<ENTERO>",
    "<FLOTANTEDOUBLE>",
    "<CLASES>",
    "<CARACTER>",
    "<CADENA>",
    "<PAQUET>",
    "<VAR>",
    "<FUNC>",
    "<LIBR>",
    "\"\\u00aa\"",
    "\"\\u00ba\"",
    "\"\\u00e7\"",
    "\"\\u00a8\"",
    "\"`\"",
    "\"\\u00b4\"",
    "\"\\\\\"",
  };

}
