/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */
package Analizador;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ENTER = 5;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int CLASS = 9;
  /** RegularExpression Id. */
  int PACK = 10;
  /** RegularExpression Id. */
  int PUBLIC = 11;
  /** RegularExpression Id. */
  int PRIVATE = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int CHAR = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int FLOAT = 18;
  /** RegularExpression Id. */
  int BOOLEAN = 19;
  /** RegularExpression Id. */
  int TRY = 20;
  /** RegularExpression Id. */
  int CATCH = 21;
  /** RegularExpression Id. */
  int SUPER = 22;
  /** RegularExpression Id. */
  int THIS = 23;
  /** RegularExpression Id. */
  int DERIVATE = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int FINAL = 26;
  /** RegularExpression Id. */
  int VOID = 27;
  /** RegularExpression Id. */
  int NULL = 28;
  /** RegularExpression Id. */
  int IMPORT = 29;
  /** RegularExpression Id. */
  int TRUE = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int SWITCH = 33;
  /** RegularExpression Id. */
  int CASE = 34;
  /** RegularExpression Id. */
  int PRINMAIN = 35;
  /** RegularExpression Id. */
  int DOUBLE = 36;
  /** RegularExpression Id. */
  int EXCEPT = 37;
  /** RegularExpression Id. */
  int DEF = 38;
  /** RegularExpression Id. */
  int LLAVA = 39;
  /** RegularExpression Id. */
  int LLAVC = 40;
  /** RegularExpression Id. */
  int CORA = 41;
  /** RegularExpression Id. */
  int CORC = 42;
  /** RegularExpression Id. */
  int PAREA = 43;
  /** RegularExpression Id. */
  int PAREC = 44;
  /** RegularExpression Id. */
  int PYC = 45;
  /** RegularExpression Id. */
  int COMSIM = 46;
  /** RegularExpression Id. */
  int COM = 47;
  /** RegularExpression Id. */
  int PUNT = 48;
  /** RegularExpression Id. */
  int GUIONB = 49;
  /** RegularExpression Id. */
  int DOSP = 50;
  /** RegularExpression Id. */
  int MAYORQ = 51;
  /** RegularExpression Id. */
  int MENORQ = 52;
  /** RegularExpression Id. */
  int MAYORI = 53;
  /** RegularExpression Id. */
  int MENORI = 54;
  /** RegularExpression Id. */
  int IGUALI = 55;
  /** RegularExpression Id. */
  int DIFER = 56;
  /** RegularExpression Id. */
  int AND = 57;
  /** RegularExpression Id. */
  int OR = 58;
  /** RegularExpression Id. */
  int NOT = 59;
  /** RegularExpression Id. */
  int INCRE = 60;
  /** RegularExpression Id. */
  int DECRE = 61;
  /** RegularExpression Id. */
  int ASIG = 62;
  /** RegularExpression Id. */
  int SUMASIG = 63;
  /** RegularExpression Id. */
  int RESASIG = 64;
  /** RegularExpression Id. */
  int MULASIG = 65;
  /** RegularExpression Id. */
  int DIVASIG = 66;
  /** RegularExpression Id. */
  int MODASIG = 67;
  /** RegularExpression Id. */
  int SUMA = 68;
  /** RegularExpression Id. */
  int RESTA = 69;
  /** RegularExpression Id. */
  int DIVIS = 70;
  /** RegularExpression Id. */
  int POTEN = 71;
  /** RegularExpression Id. */
  int MODUL = 72;
  /** RegularExpression Id. */
  int MULTI = 73;
  /** RegularExpression Id. */
  int letraMay = 74;
  /** RegularExpression Id. */
  int letraMin = 75;
  /** RegularExpression Id. */
  int c = 76;
  /** RegularExpression Id. */
  int c2 = 77;
  /** RegularExpression Id. */
  int digito = 78;
  /** RegularExpression Id. */
  int ENTERO = 79;
  /** RegularExpression Id. */
  int FLOTANTEDOUBLE = 80;
  /** RegularExpression Id. */
  int CLASES = 81;
  /** RegularExpression Id. */
  int CARACTER = 82;
  /** RegularExpression Id. */
  int CADENA = 83;
  /** RegularExpression Id. */
  int PAQUET = 84;
  /** RegularExpression Id. */
  int VAR = 85;
  /** RegularExpression Id. */
  int FUNC = 86;
  /** RegularExpression Id. */
  int LIBR = 87;
  /** RegularExpression Id. */
  int ENTEROINV = 88;
  /** RegularExpression Id. */
  int FLOTDOBINV = 89;
  /** RegularExpression Id. */
  int CADENAINV = 90;
  /** RegularExpression Id. */
  int A = 91;
  /** RegularExpression Id. */
  int GRADOS = 92;
  /** RegularExpression Id. */
  int CPOR = 93;
  /** RegularExpression Id. */
  int PUNTOS = 94;
  /** RegularExpression Id. */
  int ACENTOI = 95;
  /** RegularExpression Id. */
  int ACENTO = 96;
  /** RegularExpression Id. */
  int BARRAI = 97;
  /** RegularExpression Id. */
  int ARROBA = 98;

  /** Lexical state. */
  int SALTO = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\n\"",
    "\"If\"",
    "\"Else\"",
    "\"While\"",
    "\"class\"",
    "\"Pack\"",
    "\"public\"",
    "\"private\"",
    "\"break\"",
    "\"do\"",
    "\"char\"",
    "\"string\"",
    "\"int\"",
    "\"float\"",
    "\"boolean\"",
    "\"Try\"",
    "\"Catch\"",
    "\"Super\"",
    "\"this\"",
    "\"Derivate\"",
    "\"return\"",
    "\"Final\"",
    "\"void\"",
    "\"null\"",
    "\"import\"",
    "\"true\"",
    "\"false\"",
    "\"For\"",
    "\"Switch\"",
    "\"Case\"",
    "\"principalMain\"",
    "\"double\"",
    "\"Except\"",
    "\"Default\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"\\\'\"",
    "\",\"",
    "\".\"",
    "\"_\"",
    "\":\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"<>\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"^\"",
    "\"%\"",
    "\"*\"",
    "<letraMay>",
    "<letraMin>",
    "<c>",
    "<c2>",
    "<digito>",
    "<ENTERO>",
    "<FLOTANTEDOUBLE>",
    "<CLASES>",
    "<CARACTER>",
    "<CADENA>",
    "<PAQUET>",
    "<VAR>",
    "<FUNC>",
    "<LIBR>",
    "<ENTEROINV>",
    "<FLOTDOBINV>",
    "<CADENAINV>",
    "\"\\u00aa\"",
    "\"\\u00ba\"",
    "\"\\u00e7\"",
    "\"\\u00a8\"",
    "\"`\"",
    "\"\\u00b4\"",
    "\"\\\\\"",
    "\"@\"",
  };

}
